before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: .
    binary: ujust-picker
    ldflags:
      - -s -w -X main.version={{.Tag}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

# Allow any tag format, not just semver
git:
  prerelease_suffix: "-pre"

release:
  draft: false
  prerelease: false

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
